[workspace]
resolver = "3"
members = [
    "template",
    "day-01",
    "day-02",
    "day-03",
    "day-04",
    "day-05",
]

[workspace.package]
description = "Advent of Code 2025"
authors = ["SteveBinary"]
version = "1.0.0"
edition = "2024"

[workspace.dependencies]
